<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zendesk\\API\\' => array($vendorDir . '/zendesk/zendesk_api_client_php/src'),
    'PEAR' => array($vendorDir . '/pear/pear_exception'),
    'Mail_mimeDecode' => array($vendorDir . '/pear/mail_mime-decode'),
    'Mail' => array($vendorDir . '/pear/mail_mime'),
    'Inflect' => array($vendorDir . '/mmucklo/inflect/src'),
    'HTTP_Request2' => array($vendorDir . '/pear/http_request2'),
    'Google_Service_' => array($vendorDir . '/google/apiclient-services/src'),
    'Google_' => array($vendorDir . '/google/apiclient/src'),
    'Console' => array($vendorDir . '/pear/console_getopt'),
    'Composer\\Installer' => array($vendorDir . '/compwright/codeigniter-installers/src'),
    '' => array($vendorDir . '/pear/pear-core-minimal/src'),
);
